### ISSUE TITLE
documentation: protocol

### ISSUE THREAD

**Issue by nyje** [prof18/CyberRobotBrain#1]
Hi, I have successfully connected to a cyber robot using python libraries. 
Is there any possibility of information from your reverse engineering of the cyber robot
bt protocol, other than the extant java code?
I'm trying to get my head around it, but am struggling...
A document listing what was discovered about the BT interface in a language independent way would be amazing ;-)

**Comment by prof18** [comment]
Hi! We found out the characteristic for the movement but there are embedded inside the java code. I think that could be a nice idea to write out a wiki or something like that

**Comment by prof18** [comment]
I've just wrote a little [wiki page](https://github.com/prof18/CyberRobotBrain/wiki/How-to-move-Cyber-Robot) to explain the BLE characteristic used for the movement.

**Comment by nyje** [comment]
That's a start, thank you for your response.
